name: Disposable cross-repository TPA release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: read
  attestations: write
  id-token: write

jobs:
  release:
    permissions:
      contents: write
      attestations: write
      id-token: write
    uses: eugen252009/tpa-reusable-deb-release-builder-test/.github/workflows/reusable-deb-release.yml@7873eb4297d640707fca064a850a73f9f469cbde
    with:
      config: .tpa-release.yml
      tpa-repository: eugen252009/tpa-reusable-deb-release-builder-test
      tpa-ref: 7873eb4297d640707fca064a850a73f9f469cbde
      tpa-version: "0.7.0"
