name: Disposable cross-repository TPA release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: read
  attestations: write
  id-token: write

jobs:
  release:
    permissions:
      contents: write
      attestations: write
      id-token: write
    uses: eugen252009/tpa-reusable-deb-release-builder-test/.github/workflows/reusable-deb-release.yml@4b29778b2f9bee391cfc72f42a119aeabab0f45e
    with:
      config: .tpa-release.yml
      tpa-repository: eugen252009/tpa-reusable-deb-release-builder-test
      tpa-ref: 4b29778b2f9bee391cfc72f42a119aeabab0f45e
      tpa-version: "0.7.0"
